apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image:us-central1-docker.pkg.dev/qwiklabs-gcp-00-e6f217c85173/my-repository/hello-cloudbuild-dev:V1.0
        ports:
        - containerPort: 8080
